name: oro_health
channels:
- conda-forge
- pytorch
dependencies:
- python==3.7
- pip
- nb_conda
- nb_conda_kernels
- scikit-learn
- matplotlib
- jupyterlab
- pandas
- mlflow
- tqdm
- pytorch
- torchvision
- tensorflow==1.14.0
- numpy
- jupyterlab_widgets
- ipywidgets
- pip:
  - timm
  - seaborn
  - opencv-python